### ISSUE TITLE
Not allowed to use C code without cgo

### ISSUE THREAD

**Issue by albertoleal** [ccding/go-logging#12]
When using this library with Go 1.4, the following error is returned: 

```bash
imports github.com/ccding/go-logging/logging: C source files not allowed when not using cgo: get_go_id.c
```

**Comment by albertoleal** [comment]
Up

**Comment by mikejd** [comment]
Same issue here.

**Comment by ccding** [comment]
I don't know what Go1.4 changed. Do you have any idea? simply delete the get_to_id.c and the calling of GetGoID function?

**Comment by mikejd** [comment]
From release notes for Go 1.4:

```Unless cgo is being used to build the package, the go command now refuses to compile C source files, since the relevant C compilers (6c etc.) are intended to be removed from the installation in some future release. (They are used today only to build part of the runtime.) It is difficult to use them correctly in any case, so any extant uses are likely incorrect, so we have disabled them.```

(http://tip.golang.org/doc/go1.4#gocmd)

**Comment by ccding** [comment]
I hope it works now, but, at the moment I don't have an environment to test them. Let me know if there is any issues.
