### ISSUE TITLE
example.go panics with invalid memory access

### ISSUE THREAD

**Issue by yihungjen** [ccding/go-logging#14]
logger1 [ ERROR]  2015-06-16 03:24:31.835820817 - this is a test from error
logger1 [ DEBUG]  2015-06-16 03:24:31.835896237 - this is a test from debug
logger1 [NOTSET]  2015-06-16 03:24:31.835905828 - orz1434425071835745336
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43ed81]

goroutine 1 [running]:
github.com/ccding/go-logging/logging.(*Logger).SetLevel(0x0, 0xa)
        /go_root/src/github.com/ccding/go-logging/logging/logging.go:254 +0x41
main.main()
        /go_root/src/github.com/ccding/go-logging/example.go:40 +0x720

goroutine 7 [runnable]:
github.com/ccding/go-logging/logging.(*Logger).watcher(0xc2080560c0)
        /go_root/src/github.com/ccding/go-logging/logging/writer.go:57 +0x808
created by github.com/ccding/go-logging/logging.createLogger
        //go_root/src/github.com/ccding/go-logging/logging/logging.go:187 +0x2f3
exit status 2

**Comment by ccding** [comment]
what's your environment? it doesn't panic in my computer

➜ CD go-logging git:(master) ✗ ./go-logging
logger1 [ ERROR]  2015-06-15 20:40:34.798033485 - this is a test from error
logger1 [ DEBUG]   2015-06-15 20:40:34.79840646 - this is a test from debug
logger1 [NOTSET]  2015-06-15 20:40:34.798431605 - orz1434426034797903918
➜ CD go-logging git:(master) ✗ go version
go version go1.3.1 darwin/amd64
➜ CD go-logging git:(master) ✗

**Comment by yihungjen** [comment]
I am running with go1.4.2 linux/amd64

Installed on docker image ubuntu 14.04

**Comment by ccding** [comment]
sorry I don't have an environment to test it. Could you please try to figure it out and send me a pull request?

**Comment by ccding** [comment]
Hi, I tried in an environment with go version go1.4.2 linux/amd64. It doesn't panic. I am not sure what happened in your computer. Could you please give me a little bit more information to help me reproduce this panic?
