### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by debraj-manna** [ccding/go-logging#15]
I want to use [Sourcegraph](https://sourcegraph.com) for go-logging code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/ccding/go-logging. (It should only take 30 seconds.)

Thank you!

**Comment by ccding** [comment]
done. thanks

**Comment by debraj-manna-jabong** [comment]
Thanks @ccding.
